name: clashilator
version: 0.1.2
category: Hardware, Development
synopsis: Automated Clash to Verilator bridge
description:
  Code generator and @Setup.hs@ hooks to generate a Verilator simulation
  and access it from Clash
author: Gergő Érdi
maintainer: gergo@erdi.hu
github: gergoerdi/clashilator
license: MIT

dependencies:
  - base >= 4.14 && < 5
  - Cabal
  - lens

  - ghc
  - clash-lib
  - clash-ghc
  - text
  - filepath
  - stache
  - aeson
  - unordered-containers
  - optparse-applicative
  - containers
  - shake

source-dirs:
  - src

ghc-options:
  - -Wunused-imports

extra-source-files:
  - README.md
  
  - template/Makefile.mustache
  - template/Interface.h.mustache
  - template/Impl.cpp.mustache
  - template/Impl.h.mustache
  - template/FFI.hsc.mustache

library:
  exposed-modules:
    - Clash.Clashilator
    - Clash.Clashilator.Setup

executables:
  clashilator:
    main: main.hs
